name: Laravel CI/CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode dari GitHub
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: mbstring, xml, ctype, json, pdo, bcmath
          coverage: none

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Setup environment
        run: cp .env.example .env

      - name: Generate key
        run: php artisan key:generate

      - name: Setup database
        run: |
          touch database/database.sqlite
          php artisan migrate --force

      - name: Run tests
        run: php artisan test
